package com.jarvis.movietracker.ui.fragment

import android.os.Bundle
import androidx.navigation.NavDirections

// Generated NavDirections classes (normally auto-generated by safe-args)
data class SearchMovieFragmentDirections(
    val movieId: Int
) : NavDirections {
    override fun getActionId(): Int = R.id.action_search_to_details
    override fun getArguments(): Bundle = Bundle().apply {
        putInt("movieId", movieId)
    }

    companion object {
        fun actionSearchToDetails(movieId: Int) = SearchMovieFragmentDirections(movieId)
    }
}

data class WatchlistFragmentDirections(
    val movieId: Int
) : NavDirections {
    override fun getActionId(): Int = R.id.action_watchlist_to_details
    override fun getArguments(): Bundle = Bundle().apply {
        putInt("movieId", movieId)
    }

    companion object {
        fun actionWatchlistToDetails(movieId: Int) = WatchlistFragmentDirections(movieId)
    }
}

data class MovieDetailsFragmentDirections(
    val movieId: Int
) : NavDirections {
    override fun getActionId(): Int = R.id.action_details_to_details
    override fun getArguments(): Bundle = Bundle().apply {
        putInt("movieId", movieId)
    }

    companion object {
        fun actionDetailsToDetails(movieId: Int) = MovieDetailsFragmentDirections(movieId)
    }
}

